/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Murillo
 * @date 14/03/2016
 */
public class ProyectoCalcu extends javax.swing.JFrame {
    // variables globales para almacenar el primer digito y realizar la operacion con el segundo y mostrar el resultado
    public float nun1 ;
    public float nun2 ;
    public float result = 0;
    public String Signo; // sirve para saber que tipo de operacion estoy realizando asi decidir que operacion 
    // ejecutar despues de pulsar el boton igual
    public float memoria = 0;
    public float porciento = 0;
    
    /**
     * Creates new form ProyectoCalcu
     */
    public ProyectoCalcu() {
        initComponents();
        setLocationRelativeTo(null);
        txtNumeros.setEnabled(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnMs = new javax.swing.JButton();
        btnComa = new javax.swing.JButton();
        btnMmas = new javax.swing.JButton();
        btnMas = new javax.swing.JButton();
        btnMmenos = new javax.swing.JButton();
        bntBorrar = new javax.swing.JButton();
        btnCe = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnMasmenos = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        txtNumeros = new javax.swing.JTextField();
        btn6 = new javax.swing.JButton();
        btnMc = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnMr = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnPor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnMenos.setText("-");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnMs.setText("MS");
        btnMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMsActionPerformed(evt);
            }
        });

        btnComa.setText(",");
        btnComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComaActionPerformed(evt);
            }
        });

        btnMmas.setText("M+");
        btnMmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMmasActionPerformed(evt);
            }
        });

        btnMas.setText("+");
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        btnMmenos.setText("M-");
        btnMmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMmenosActionPerformed(evt);
            }
        });

        bntBorrar.setText("<-");

        btnCe.setText("CE");
        btnCe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeActionPerformed(evt);
            }
        });

        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnMasmenos.setText("+/-");
        btnMasmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasmenosActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        txtNumeros.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        txtNumeros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerosActionPerformed(evt);
            }
        });
        txtNumeros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumerosKeyTyped(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btnMc.setText("MC");
        btnMc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMcActionPerformed(evt);
            }
        });

        btnMulti.setText("*");
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });

        btnMr.setText("MR");
        btnMr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMrActionPerformed(evt);
            }
        });

        btnMod.setText("MOD");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btnPor.setText("%");
        btnPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNumeros)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnMc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bntBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnCe))
                                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnComa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMasmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMmas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMmas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMmenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntBorrar)
                    .addComponent(btnCe)
                    .addComponent(btnC)
                    .addComponent(btnMasmenos))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7)
                    .addComponent(btn8)
                    .addComponent(btn9)
                    .addComponent(btnDiv)
                    .addComponent(btnPor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4)
                    .addComponent(btn5)
                    .addComponent(btn6)
                    .addComponent(btnMulti)
                    .addComponent(btnMod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn1)
                            .addComponent(btn2)
                            .addComponent(btn3)
                            .addComponent(btnMenos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn0)
                            .addComponent(btnComa)
                            .addComponent(btnMas)))
                    .addComponent(btnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  //Elimina cualquier número almacenado en memoria.
    private void btnMcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMcActionPerformed
       memoria = 0;
       JOptionPane.showMessageDialog(null, "Memoria vacia");
    }//GEN-LAST:event_btnMcActionPerformed

    private void txtNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerosActionPerformed

    private void txtNumerosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerosKeyTyped
    /**
     * 
     * @date of modification 21/03/2016
     * Creamos los eventos action performance de todos los botones con numeros para
     * darles la funcion de cuando se precione alguno 
     * en cada buton si el campo de texto llega a sus 10 digitos el se bloquea y no permite el ingreso de mas
     * 
     */
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (result != 0 ){ txtNumeros.setText("");}
        if (txtNumeros.getText().length()>=10){
            txtNumeros.enableInputMethods(false);
        }else{
       txtNumeros.setText(txtNumeros.getText() + "1");
        }
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if (result != 0 ){ txtNumeros.setText("");}
         if (txtNumeros.getText().length()>=10){
            txtNumeros.enableInputMethods(false);
        }else{
        txtNumeros.setText(txtNumeros.getText() + "2");
         }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if (result != 0 ){ txtNumeros.setText("");}
         if (txtNumeros.getText().length()>=10){
            txtNumeros.enableInputMethods(false);
        }else{
        txtNumeros.setText(txtNumeros.getText() + "3");
         }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if (result != 0 ){ txtNumeros.setText("");}
         if (txtNumeros.getText().length()>=10){
            txtNumeros.enableInputMethods(false);
        }else{
        txtNumeros.setText(txtNumeros.getText() + "4");
         }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if (result != 0 ){ txtNumeros.setText("");}
         if (txtNumeros.getText().length()>=10){
            txtNumeros.enableInputMethods(false);
        }else{
        txtNumeros.setText(txtNumeros.getText() + "5");
         }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if (result != 0 ){ txtNumeros.setText("");}
         if (txtNumeros.getText().length()>=10){
            txtNumeros.enableInputMethods(false);
        }else{
        txtNumeros.setText(txtNumeros.getText() + "6");
         }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if (result != 0 ){ txtNumeros.setText("");}
         if (txtNumeros.getText().length()>=10){
            txtNumeros.enableInputMethods(false);
        }else{
        txtNumeros.setText(txtNumeros.getText() + "7");
         }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if (result != 0 ){ txtNumeros.setText("");}
         if (txtNumeros.getText().length()>=10){
            txtNumeros.enableInputMethods(false);
        }else{
        txtNumeros.setText(txtNumeros.getText() + "8");
         }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if (result != 0 ){ txtNumeros.setText("");}
         if (txtNumeros.getText().length()>=10){
            txtNumeros.enableInputMethods(false);
        }else{
        txtNumeros.setText(txtNumeros.getText() + "9");
         }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        if (result != 0 ){ txtNumeros.setText("");}
         if (txtNumeros.getText().length()>=10){
            txtNumeros.enableInputMethods(false);
        }else{
        txtNumeros.setText(txtNumeros.getText() + "0");
         } 
    }//GEN-LAST:event_btn0ActionPerformed
    /**
     * borra todo calculo y pone la pantalla en cero para inicia otra operacion 
     * y habilita el campo de texto si esta desabilidato
    **/ 
    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        
        txtNumeros.enableInputMethods(true);
        txtNumeros.setText("");
        btnMas.setEnabled(true);
        btnMenos.setEnabled(true);
        btnDiv.setEnabled(true);
        btnMulti.setEnabled(true);
        btnMod.setEnabled(true);
    }//GEN-LAST:event_btnCActionPerformed

    private void btnComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComaActionPerformed
        // TODO add your handling code here:
        if (txtNumeros.getText().length() <= 0 ){
            txtNumeros.setText("0.");
        }else if (hayPunto() == false){
          txtNumeros.setText(txtNumeros.getText()+ ".");
        }else{
        JOptionPane.showMessageDialog(null, "Ya existe punto");
        }
  
    }//GEN-LAST:event_btnComaActionPerformed
// boton de suma y le decimos a la variable signo que sea igual a suma
    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        if (porciento != 0){
              nun1=nun1;
              btnMas.setEnabled(false);
              Signo = "suma"; 
        }else if (txtNumeros.getText().length() != 0 ){
        nun1 = Float.parseFloat(txtNumeros.getText());
        btnMas.setEnabled(false);
        txtNumeros.setText("");
        Signo = "suma"; 
      }else{JOptionPane.showMessageDialog(null, "Debe digitar un numero");
      }
      
    }//GEN-LAST:event_btnMasActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        if (porciento != 0){
        nun2 = porciento;
        }else{       
        nun2 = Float.parseFloat(txtNumeros.getText());
        }
        if (Signo.equals("suma")){
            result = nun1 + nun2;
            txtNumeros.setText(String.valueOf(result));    
        } else if (Signo.equals("resta")){
            result = nun1 - nun2;
            txtNumeros.setText(String.valueOf(result));
        } else if (Signo.equals("multiplicacion")){
            result = nun1 * nun2;
            txtNumeros.setText(String.valueOf(result));
        }else if (Signo.equals("division")){
            result = nun1 / nun2;
            txtNumeros.setText(String.valueOf(result));
        }else if (Signo.equals("mod")){
            result = nun1 % nun2;
            txtNumeros.setText(String.valueOf(result));}
        btnMas.setEnabled(true);
        btnMenos.setEnabled(true);
        btnDiv.setEnabled(true);
        btnMulti.setEnabled(true);
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
       if (txtNumeros.getText().length() == 0 ){
           JOptionPane.showMessageDialog(null, "Debe digitar un numero");
       }else if (!txtNumeros.getText().equals("0")){
        nun1 = Float.parseFloat(txtNumeros.getText());
        btnDiv.setEnabled(false);
        txtNumeros.setText("");
        Signo = "division";
        }else {
        JOptionPane.showMessageDialog(null, "No se permite la división entre 0");
        txtNumeros.setText("");
        }
        
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        if (porciento != 0){
              nun1=nun1;
              btnMenos.setEnabled(false);
              Signo = "suma"; 
        }else if (txtNumeros.getText().length() != 0 ){
        nun1 = Float.parseFloat(txtNumeros.getText());
        btnMenos.setEnabled(false);
        txtNumeros.setText("");
        Signo = "resta";
        }else{JOptionPane.showMessageDialog(null, "Debe digitar un numero");
      }
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        if (txtNumeros.getText().length() != 0 ){
        nun1 = Float.parseFloat(txtNumeros.getText());
        btnMulti.setEnabled(false);
        txtNumeros.setText("");
        Signo = "multiplicacion";
        }else{JOptionPane.showMessageDialog(null, "Debe digitar un numero");
      }
    }//GEN-LAST:event_btnMultiActionPerformed
//Recupera el número almacenado en memoria. El número permanece en memoria.
    private void btnMrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMrActionPerformed
     txtNumeros.setText(String.valueOf(memoria));  
        btnMas.setEnabled(true);
        btnMenos.setEnabled(true);
        btnDiv.setEnabled(true);
        btnMulti.setEnabled(true);
    }//GEN-LAST:event_btnMrActionPerformed
  // Almacena en memoria el número mostrado.
    private void btnMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMsActionPerformed
       memoria = Float.parseFloat(txtNumeros.getText());
     //  JOptionPane.showMessageDialog(null, "Numero almacenado con éxito");
    }//GEN-LAST:event_btnMsActionPerformed
    /**
     * Suma el número mostrado a otro número que se encuentre en memoria pero no
     * muestra la suma de estos números y almacena el resultado en memoria .
     * 
     */
    private void btnMmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMmasActionPerformed
     memoria = memoria + Float.parseFloat(txtNumeros.getText());
    // JOptionPane.showMessageDialog(null,"Calculo realizado con éxito");
    }//GEN-LAST:event_btnMmasActionPerformed

    private void btnMmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMmenosActionPerformed
       memoria = memoria - Float.parseFloat(txtNumeros.getText());
    //JOptionPane.showMessageDialog(null,"Calculo realizado con éxito");
    }//GEN-LAST:event_btnMmenosActionPerformed
    //Elimina el número mostrado.
    private void btnCeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeActionPerformed
     txtNumeros.setText("");
    }//GEN-LAST:event_btnCeActionPerformed

    private void btnMasmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasmenosActionPerformed
        // TODO add your handling code here:
        // Not Found
    }//GEN-LAST:event_btnMasmenosActionPerformed

    private void btnPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorActionPerformed
       nun2 = Float.parseFloat(txtNumeros.getText());
       porciento = (nun2/100)*nun1; 
       btnMulti.setEnabled(true);
       txtNumeros.setText(String.valueOf(porciento));
       
       
    }//GEN-LAST:event_btnPorActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        if (txtNumeros.getText().length() != 0 ){
        nun1 = Float.parseFloat(txtNumeros.getText());
        btnMod.setEnabled(false);
        txtNumeros.setText("");
        Signo = "mod";
        }else{JOptionPane.showMessageDialog(null, "Debe digitar un numero");
      }
    }//GEN-LAST:event_btnModActionPerformed
   /**
    * 
    * metodo que me retorna si existe un punto ya dentro 
    * del campo de texto donde estan los numeros 
    */
    public boolean hayPunto (){
      boolean punto = false;
      String cadena = txtNumeros.getText();
      
        for (int i = 0; i < cadena.length() ; i++) {
            
        if (cadena.substring(i, i + 1).equals (".")){
            punto = true;
            break;
        }else{
        punto = false;
        }           
        }
    return punto;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoCalcu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBorrar;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCe;
    private javax.swing.JButton btnComa;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMasmenos;
    private javax.swing.JButton btnMc;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnMmas;
    private javax.swing.JButton btnMmenos;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnMr;
    private javax.swing.JButton btnMs;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnPor;
    private javax.swing.JTextField txtNumeros;
    // End of variables declaration//GEN-END:variables
}
